# Generated by Django 5.0.6 on 2024-05-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctionlisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
